Restyled by shellharden

diff --git a/macosx/hbsign b/macosx/hbsign
--- a/macosx/hbsign
+++ b/macosx/hbsign
@@ -26,10 +26,10 @@ set -e
 set -u
 
 SELF="${0}"
-SELF_NAME=$(basename "${SELF}")
+SELF_NAME=$(basename "$SELF")
 HELP="\
-usage: ${SELF_NAME} [-hrs]
-       ${SELF_NAME} identity application [application2 ...]
+usage: $SELF_NAME [-hrs]
+       $SELF_NAME identity application [application2 ...]
 where:
    -h  display this help text
    -r  enable runtime hardening
@@ -40,25 +40,25 @@ where:
 function exit_with_error {
     set +e
     ERROR="${2}"
-    echo "${SELF_NAME}: ${ERROR}" >&2
+    echo "$SELF_NAME: $ERROR" >&2
     PRINT_HELP="${3:-false}"
     if [[ "${PRINT_HELP}" == true ]]; then
-        echo -e "${HELP}"
+        echo -e "$HELP"
     fi
     exit "${1}"
 }
 
-LOG="${NAME}.log"
-touch "${LOG}" || exit_with_error 1 "${SELF_NAME}: unable to create log file ${LOG}"
+LOG="$NAME.log"
+touch "$LOG" || exit_with_error 1 "$SELF_NAME: unable to create log file $LOG"
 
 OPTIND=1
 RUNTIME=false
 SANDBOX=false
 while getopts ":hrs" OPT; do
-    case "${OPT}" in
+    case "$OPT" in
         h)
             # Print help and exit
-            echo -e "${HELP}"
+            echo -e "$HELP"
             exit 0
             ;;
         r)
@@ -69,26 +69,26 @@ while getopts ":hrs" OPT; do
             ;;
         :)
             # Option without required argument
-            exit_with_error 1 "${SELF_NAME}: option -${OPTARG} requires a value" true
+            exit_with_error 1 "$SELF_NAME: option -$OPTARG requires a value" true
             ;;
         \?)
             # Invalid option specified
-            exit_with_error 1 "${SELF_NAME}: invalid option: -${OPTARG}" true
+            exit_with_error 1 "$SELF_NAME: invalid option: -$OPTARG" true
             ;;
     esac
 done
 shift $((${OPTIND} - 1))
 IDENTITY="${1:-}"
 if [[ "${IDENTITY}" == '' ]]; then
-    exit_with_error 1 "${SELF_NAME}: identity not specified" true
+    exit_with_error 1 "$SELF_NAME: identity not specified" true
 fi
 shift 1
 
 if [[ ${#@} -eq 0 ]]; then
-    exit_with_error 1 "${SELF_NAME}: application not specified" true
+    exit_with_error 1 "$SELF_NAME: application not specified" true
 fi
 
-SCRIPTDIR=$(dirname "${SELF}")
+SCRIPTDIR=$(dirname "$SELF")
 
 
 RUNTIME_FLAGS=""
@@ -107,97 +107,97 @@ if [[ "${SANDBOX}" == true ]]; then
 elif [[ "${RUNTIME}" == true ]]; then
     ENTITLEMENTS_MAIN_FLAGS="--entitlements $SCRIPTDIR/HandBrake-RuntimeOnly.entitlements"
     ENTITLEMENTS_XPC_FLAGS="--entitlements $SCRIPTDIR/HandBrakeXPCService/HandBrakeXPCService-RuntimeOnly.entitlements"
-    ENTITLEMENTS_CLI_FLAGS="${ENTITLEMENTS_XPC_FLAGS}"
+    ENTITLEMENTS_CLI_FLAGS="$ENTITLEMENTS_XPC_FLAGS"
 fi
 
 function sign {  # sign flags target
     local TARGET FLAGS ERR
     TARGET="${2:-}"
     if [[ "${TARGET}" == "" ]]; then
-        ERR="${SELF_NAME}: target not specified to sign function\ncommand was: sign ${1:-} ${2:-}"
-        echo -e "${ERR}" >> "${LOG}"
-        exit_with_error 1 "${ERR}"
+        ERR="$SELF_NAME: target not specified to sign function\ncommand was: sign ${1:-} ${2:-}"
+        echo -e "$ERR" >> "$LOG"
+        exit_with_error 1 "$ERR"
     fi
 
     FLAGS="${1:-}"
     if [[ "${FLAGS}" == "main" ]]; then
-        codesign --force --verbose $RUNTIME_FLAGS $ENTITLEMENTS_MAIN_FLAGS -s "${IDENTITY}" "${2:-}" >>"${LOG}" 2>&1 || exit_with_error 1 "Signing failed. More info may be available in ${LOG}"
+        codesign --force --verbose "$RUNTIME_FLAGS" "$ENTITLEMENTS_MAIN_FLAGS" -s "$IDENTITY" "${2:-}" >>"$LOG" 2>&1 || exit_with_error 1 "Signing failed. More info may be available in $LOG"
     elif [[ "${FLAGS}" == "xpc" ]]; then
-        codesign --force --verbose $RUNTIME_FLAGS $ENTITLEMENTS_XPC_FLAGS -s "${IDENTITY}" "${2:-}" >>"${LOG}" 2>&1 || exit_with_error 1 "Signing failed. More info may be available in ${LOG}"
+        codesign --force --verbose "$RUNTIME_FLAGS" "$ENTITLEMENTS_XPC_FLAGS" -s "$IDENTITY" "${2:-}" >>"$LOG" 2>&1 || exit_with_error 1 "Signing failed. More info may be available in $LOG"
     elif [[ "${FLAGS}" == "cli" ]]; then
-        codesign --force --verbose $RUNTIME_FLAGS $ENTITLEMENTS_CLI_FLAGS --prefix fr.handbrake. -s "${IDENTITY}" "${2:-}" >>"${LOG}" 2>&1 || exit_with_error 1 "Signing failed. More info may be available in ${LOG}"
+        codesign --force --verbose "$RUNTIME_FLAGS" "$ENTITLEMENTS_CLI_FLAGS" --prefix fr.handbrake. -s "$IDENTITY" "${2:-}" >>"$LOG" 2>&1 || exit_with_error 1 "Signing failed. More info may be available in $LOG"
     else
-        codesign --force --verbose $RUNTIME_FLAGS -s "${IDENTITY}" "${2:-}" >>"${LOG}" 2>&1 || exit_with_error 1 "Signing failed. More info may be available in ${LOG}"
+        codesign --force --verbose "$RUNTIME_FLAGS" -s "$IDENTITY" "${2:-}" >>"$LOG" 2>&1 || exit_with_error 1 "Signing failed. More info may be available in $LOG"
     fi
 }
 
-echo "Script dir: ${SCRIPTDIR}"
-echo "Identity: ${IDENTITY}"
-echo "Hardened runtime: ${RUNTIME}"
-echo "Sandbox: ${SANDBOX}"
+echo "Script dir: $SCRIPTDIR"
+echo "Identity: $IDENTITY"
+echo "Hardened runtime: $RUNTIME"
+echo "Sandbox: $SANDBOX"
 
 for TARGET in "${@}"; do
 
     TARGET="${TARGET#./}"
-    echo "${TARGET}:"
+    echo "$TARGET:"
 
     if [[ "${TARGET##*/}" == 'HandBrake.app' ]]; then
         echo "  Signing Frameworks"
-        find "${TARGET}"/Contents/Frameworks -type f -name ".DS_Store" -exec rm '{}' \; >/dev/null 2>&1
-        find "${TARGET}"/Contents/Frameworks -type f -name "*.textile" -exec rm '{}' \; >/dev/null 2>&1
-        find "${TARGET}"/Contents/Frameworks -type f -name "*.txt" -exec rm '{}' \; >/dev/null 2>&1
-        sign "default" "${TARGET}"/Contents/Frameworks/HandBrakeKit.framework/Versions/A
-        sign "default" "${TARGET}"/Contents/Frameworks/Sparkle.framework/Resources/Autoupdate
-        sign "default" "${TARGET}"/Contents/Frameworks/Sparkle.framework/Resources/Updater.app
-        sign "default" "${TARGET}"/Contents/Frameworks/Sparkle.framework/Versions/A
-        for FILE in $(find "${TARGET}"/Contents/Frameworks -type f -name "*.h" -o -name "*.nib" -o -name "*.plist" -o -name "*.strings" -exec echo {} \; >/dev/null 2>&1)
+        find "$TARGET"/Contents/Frameworks -type f -name ".DS_Store" -exec rm '{}' \; >/dev/null 2>&1
+        find "$TARGET"/Contents/Frameworks -type f -name "*.textile" -exec rm '{}' \; >/dev/null 2>&1
+        find "$TARGET"/Contents/Frameworks -type f -name "*.txt" -exec rm '{}' \; >/dev/null 2>&1
+        sign "default" "$TARGET"/Contents/Frameworks/HandBrakeKit.framework/Versions/A
+        sign "default" "$TARGET"/Contents/Frameworks/Sparkle.framework/Resources/Autoupdate
+        sign "default" "$TARGET"/Contents/Frameworks/Sparkle.framework/Resources/Updater.app
+        sign "default" "$TARGET"/Contents/Frameworks/Sparkle.framework/Versions/A
+        for FILE in "$(find "$TARGET"/Contents/Frameworks -type f -name "*.h" -o -name "*.nib" -o -name "*.plist" -o -name "*.strings" -exec echo {} \; >/dev/null 2>&1)"
         do
-            sign "default" "${FILE}"
+            sign "default" "$FILE"
         done
 
         echo "  Signing Headers"
-        for FILE in $(find "${TARGET}"/Contents/MacOS/include -type f -exec echo {} \; >/dev/null 2>&1)
+        for FILE in "$(find "$TARGET"/Contents/MacOS/include -type f -exec echo {} \; >/dev/null 2>&1)"
         do
-            sign "default" "${FILE}"
+            sign "default" "$FILE"
         done
 
         echo "  Signing XPC Services"
-        sign "xpc"     "${TARGET}"/Contents/XPCServices/HandBrakeXPCService.xpc
-        sign "default" "${TARGET}"/Contents/XPCServices/org.sparkle-project.Downloader.xpc
-        sign "default" "${TARGET}"/Contents/XPCServices/org.sparkle-project.InstallerConnection.xpc
-        sign "default" "${TARGET}"/Contents/XPCServices/org.sparkle-project.InstallerLauncher.xpc
-        sign "default" "${TARGET}"/Contents/XPCServices/org.sparkle-project.InstallerStatus.xpc
+        sign "xpc"     "$TARGET"/Contents/XPCServices/HandBrakeXPCService.xpc
+        sign "default" "$TARGET"/Contents/XPCServices/org.sparkle-project.Downloader.xpc
+        sign "default" "$TARGET"/Contents/XPCServices/org.sparkle-project.InstallerConnection.xpc
+        sign "default" "$TARGET"/Contents/XPCServices/org.sparkle-project.InstallerLauncher.xpc
+        sign "default" "$TARGET"/Contents/XPCServices/org.sparkle-project.InstallerStatus.xpc
     fi
 
     echo "  Signing Executable"
     if [[ "${TARGET##*/}" == 'HandBrakeCLI' ]]; then
-        sign "cli" "${TARGET}"
+        sign "cli" "$TARGET"
     else
-        sign "main" "${TARGET}"
+        sign "main" "$TARGET"
     fi
 
     if [[ "${TARGET##*/}" == 'HandBrake.app' ]]; then
         echo "  Validating Frameworks"
-        codesign --verify -vv "${TARGET}"/Contents/Frameworks/HandBrakeKit.framework >>"${LOG}" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in ${LOG}"
-        codesign --verify -vv "${TARGET}"/Contents/Frameworks/Sparkle.framework >>"${LOG}" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in ${LOG}"
+        codesign --verify -vv "$TARGET"/Contents/Frameworks/HandBrakeKit.framework >>"$LOG" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in $LOG"
+        codesign --verify -vv "$TARGET"/Contents/Frameworks/Sparkle.framework >>"$LOG" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in $LOG"
 
         echo "  Validating Updater.app"
-        codesign --verify -vv "${TARGET}"/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/Updater.app >>"${LOG}" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in ${LOG}"
+        codesign --verify -vv "$TARGET"/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/Updater.app >>"$LOG" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in $LOG"
 
         echo "  Validating XPC Services"
-        codesign --verify -vv "${TARGET}"/Contents/XPCServices/HandBrakeXPCService.xpc >>"${LOG}" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in ${LOG}"
-        codesign --verify -vv "${TARGET}"/Contents/XPCServices/org.sparkle-project.Downloader.xpc >>"${LOG}" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in ${LOG}"
-        codesign --verify -vv "${TARGET}"/Contents/XPCServices/org.sparkle-project.InstallerConnection.xpc >>"${LOG}" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in ${LOG}"
-        codesign --verify -vv "${TARGET}"/Contents/XPCServices/org.sparkle-project.InstallerLauncher.xpc >>"${LOG}" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in ${LOG}"
-        codesign --verify -vv "${TARGET}"/Contents/XPCServices/org.sparkle-project.InstallerStatus.xpc >>"${LOG}" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in ${LOG}"
+        codesign --verify -vv "$TARGET"/Contents/XPCServices/HandBrakeXPCService.xpc >>"$LOG" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in $LOG"
+        codesign --verify -vv "$TARGET"/Contents/XPCServices/org.sparkle-project.Downloader.xpc >>"$LOG" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in $LOG"
+        codesign --verify -vv "$TARGET"/Contents/XPCServices/org.sparkle-project.InstallerConnection.xpc >>"$LOG" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in $LOG"
+        codesign --verify -vv "$TARGET"/Contents/XPCServices/org.sparkle-project.InstallerLauncher.xpc >>"$LOG" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in $LOG"
+        codesign --verify -vv "$TARGET"/Contents/XPCServices/org.sparkle-project.InstallerStatus.xpc >>"$LOG" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in $LOG"
     fi
 
     echo "  Validating Bundle"
-    codesign --verify --deep --strict --verbose=4 "${TARGET}" >>"${LOG}" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in ${LOG}"
+    codesign --verify --deep --strict --verbose=4 "$TARGET" >>"$LOG" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in $LOG"
 
     if [[ "${TARGET##*/}" != 'HandBrakeCLI' ]]; then
         echo "  Validating Execution Privileges"
-        spctl -a -t exec -vv "${TARGET}" >>"${LOG}" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in ${LOG}"
+        spctl -a -t exec -vv "$TARGET" >>"$LOG" 2>&1 || exit_with_error 1 "Validation failed. More info may be available in $LOG"
     fi
 
 done
